apiVersion: v1
kind: Service
metadata:
  name: {{ include "rabbit-x.fullname" . }}
  labels:
    {{- include "rabbit-x.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port1 }}
      targetPort: 5672
      protocol: TCP
      name: amqp
    - port: {{ .Values.service.port2 }}
      targetPort: 15672
      protocol: TCP
      name: mgmt-ui
    - port: {{ .Values.service.port3 }}
      targetPort: 4369
      protocol: TCP
      name: epmd
  selector:
    {{- include "rabbit-x.selectorLabels" . | nindent 4 }}
