apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-svc
  namespace: rabbitmq-ns
spec:
  #  clusterIP: None
  selector: 
    app:  rabbitmq
  ports:
  - name: rabbit-main
    protocol: TCP
    port: 5672
    targetPort: 5672
  - name: rabbitmq-gui
    protocol: TCP
    port: 15672
    targetPort: 15672
  - name: epmd
    protocol: TCP
    port: 4369
    targetPort: 4369
  type: ClusterIP

